# Site settings
author: Jesse Byers
title: Code
header-img: img/home-bg.png
email: jesse.s.byers@gmail.com
copyright_name: Jesse Byers
description: > # this means to ignore newlines until "baseurl:"
  Reflections on Coding, and Science Education
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jessesbyers

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
